spring.application.name=plens
server.port=8080
spring.datasource.url=jdbc:mysql://localhost:3306/projectlens
spring.datasource.username=root
spring.datasource.password=Vyshu@2005
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
projectlens.evaluation.alignment-threshold=70
projectlens.evaluation.overlap-threshold=60
