spring:
  datasource:
    url: jdbc:mysql://localhost:3306/projectlens?createDatabaseIfNotExist=true
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 8080
